name: Convert Word to PDF

on:
  push:
    branches:
      - main
    paths:
      - '**/*.docx'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-latex-recommended

      - name: Convert DOCX to PDF
        run: |
          for file in $(find . -name '*.docx'); do
            filename="${file%.*}"
            pandoc "$file" -o "${filename}.pdf"
          done

      - name: Commit and push PDFs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add '*.pdf'
          git commit -m "Add generated PDF(s) from DOCX" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


